DevCycleHQ/go-server-sdk

client.go, configmanager.go, configuration.go, eventqueue.go, localbucketing.go
Fix the default value for the events queue by passing around the HttpConfiguration object derived from the client options, which contains the correct values for the base CDN and events API URLs.
=> fix: use httpconfiguration base URLs for events and config manager

api_devcycle.go, client.go, configuration.go, example/local/main.go
How it works:
- The user can choose to pass in an "OnInitializedChannel" into DVCOptions
- If this channel exists then the initialization process will be run in a go routine, meaning client calls can be made before the bucketing lib is initialized
- The user can listen on the channel to block the main process until init is complete
- By not passing in the channel param the sdk will behave the same as it did before
=> add oninitialized channel that allows the user to make calls before the client is initialized

client.go, eventqueue.go, localbucketing.go, model_bucketed_user_config.go, model_platformdata.go, model_user_data.go
- re-use a global "platformData" object for cloud requests
- eliminate concept of "populatedUser" for local bucketing because DVCPopulatedUser is already implemented in WASM, and platform data being passed in was a duplicate.
=> use a single global allocation of platform data for cloud requests

client.go
- use a buffered channel for the internal initialization system to prevent blocking on writes
- only wait on initialization channel if initialized is false
- change definition of isInitialized to always be true when initialization has finished, even if it was unsuccessful
- change methods like Variable to directly check for whether a config exists rather than checking isInitialized
- increase buffer size of config stop polling channel to prevent problems with calling close when a 403 was received.
=> fix issues with close logic 

localbucketing.go
Recover from panic during `StoreConfig` when invalid config data is submitted.
=> handle invalid config

client.go, client_test.go, configmanager.go, eventqueue_test.go, localbucketing.go, logger.go
Not being able to configure this was making it such that our system had messages that weren't traceable to the service using them, or able to discard them. It was causing a lot of noise in our running system. 
I didn't really do much to look at the contents of the messages, just how they were sending. 
Also, I touched up some errors I saw around ineffectual assignment and some other small errors my linter caught.
=> move to global logger

configmanager.go, eventqueue.go
I had these deployed in our staging environment and noticed that it was kinda noisy. 
re: flush - this is debug level info imho. 
re: unchanged - there is an existing 'updated the config' statement and error notifications
=> slim down some logging

client.go, configmanager.go, eventqueue.go, localbucketing.go, localbucketing_test.go, logger.go
- if calling `variable` before init, log a `aggVariableDefaulted` event
- change deferred initialization to only defer the actual config HTTP call, but synchronously instantiate everything else.
=> fix: log variable defaulted event when calling variable before init

localbucketing.go
- Store pointer references to exported functions in WASM rather than retrieving them again each time.
=> chore: optimize function pointer allocation

localbucketing.go
Implement @paulo 's changes to reading strings out of WASM by preallocating the desired memory size and using byte arrays instead of strings.
=> Byte array reads

client.go, configmanager.go, eventqueue.go, localbucketing.go, localbucketing_test.go
Isolate the local bucketing module more by removing its ownership over the event queue. this should help reorganize things for thread pooling
=> refactor local bucketing module to remove ownership over event queue

bucketing_pool_object.go, eventqueue.go, localbucketing.go
- remove channel callback system for receiving event flush results, and return them directly
- handle all results using a single mutex
- handle results the same way for both the global and pooled local bucketing instances
=> stop using channel to handle flush results and unify result handling

localbucketing.go
cleaning up some of the WASM functions that were replaced by new versions for the protobuf and UTF8 encoding changes
=> Removing old WASM function references

bucketing_pool.go, client.go, configmanager.go, configmanager_test.go, testing_helpers.go
This PR restructures EnvironmentConfigManager to make it a bit easier to test, then expands the criteria under which we retry a config request.
Previously we only retried once for 500-level HTTP status codes, now we also retry on connection error, DNS error, etc. and unexpected HTTP statuses. When the retries are exhausted, we still return the error to the client, unless it's a 500 status.
=> DVC-6813: Retry config fetching on network error

client.go, client_test.go
I noticed this error while testing config loading. The current WASM appears to require config to be loaded in order to track events. We were only gating these calls on the SDK being initialized, but not the config loading successfully.
```
Error Message calling queueEvent: err: [error while executing at wasm backtrace:    0: 0xe756 - <unknown>!<wasm function 172>    1: 0x29805 - <unknown>!<wasm function 466>Caused by:    wasm trap: wasm `unreachable` instruction executed] errorMessage:[WASM Error: Config data is not set. at assembly/managers/configDataManager.ts:11:9]
```
=> Fix WASM error when Track called before config loads

client.go, client_test.go, configuration.go
Added validation to the options to throw an error when combinations of options will result in the client being in an unsafe state. In this case if you set an OnInitialized channel and EnableCloudBucketing=true, then listen on the channel it will hang indefinitely
=> DVC-6664 - validate client options

bucketing_pool_object.go, client.go, client_native.go, client_wasm.go, configmanager.go, configmanager_test.go, eventqueue.go, localbucketing.go, localbucketing_test.go, native_bucketing/bucketing.go
This refactors the DVCClient so that the WASM and object pool related code is now contained inside a new wrapper type, WASMLocalBucketing.
=> Extract wasm logic from DVCClient into a new wrapper

.github/workflows/bench.yml
A new action that will run the benchmark tests for variables and use the 3rd party `github-action-benchmark` action compare benchmarks against the previous cached version and report errors when the variable performance is off by 25% or higher
The plugin sets the benchmark results as comments on the commit that trigger the warning/error.
=> DVC-6656 Add benchmark GitHub action

.github/workflows/bench.yml, api/model_platformdata.go, api/model_user_data.go, api/version.go, client_native_bucketing.go, localbucketing.go, native_bucketing/datamanager_platform.go, version.go
Also tweaks private custom data - but the goal here is to be a rough impl with no concerns for threadsafety currently.
=> DVC-6784 - Client Custom Data

api/model_platformdata.go, api/model_user_data.go, api/version.go, bucketing_pool.go, bucketing_pool_factory.go, bucketing_pool_object.go, client.go, client_native_bucketing.go, client_wasm_bucketing.go, localbucketing.go, localbucketing_test.go, native_bucketing/bucketing_test.go, native_bucketing/datamanager_platform.go, version.go
Refactored how the platformData is set into the bucketing code so it is now pushed by the DVCClient explicitly.
- Now loads the data into the native bucketing properly
- Required adding it to the entire execution chain for the WASM object pool
=> DEV-7024: Fix issues with SetPlatformData in native bucketing

client.go, client_native_bucketing.go, native_bucketing/bucketing.go
We don't expect variable calls to ever return errors, or log when something unexpected happens other than a type mismatch.
This error silencing is basically in line with what the Node SDK does, but at some point we might want to look through the errors and see if any of them represent conditions where we'd still want to log something.
=> Prevent errors from being surfaced to the client in variable calls

api/model_user_data.go, client_native_bucketing.go
Setup native SDK to not call time.now() when it calls  createPopulatedUser() as native bucketing never users the createdDate value
=> DVC-7067 - optimized createPopulatedUser()

native_bucketing/model_config_body.go, native_bucketing/model_filters.go, native_bucketing/model_target.go
- Moved sorting of the distributions to config parsing
- Fixed some filtering code that didn't use the precompiled slices of values and resulted in a lot of allocations
```
BenchmarkDVCClient_VariableSerial-12    	19352398	       614.4 ns/op	     384 B/op	       2 allocs/op
```
=> Optimization in bucketing and segmentation

native_bucketing/bucketing.go, native_bucketing/model_feature_configuration.go, native_bucketing/model_filters.go, native_bucketing/model_filters_test.go
The implementation here was mixing up string contains vs. equals, which also slowed things down in the latter case.
=> Fix contains vs equals in string filters

api/model_environment.go, api/model_public_project.go, native_bucketing/config_manager.go, native_bucketing/config_manager_test.go, native_bucketing/model_config_body.go, native_bucketing/model_config_body_test.go
This isn't adding much in the way of safety, but it at least validates most of the same high-level fields as the other SDKs.
=> Add extra validation and tests to config

bucketing_pool.go, client.go, client_native_bucketing.go, configmanager.go, event_manager.go, native_bucketing/event_queue.go, request.go, util/logger_debug.go, util/logger_disabled.go, wasm_bucketing.go
Turning off the logs by default in #190 meant that some formatted errors would have lost their messages. I replaced the combination log + return error helper `util.Errorf` with just an error log, and created errors separately here. It was a lot of not very important changes, so I broke it out into a separate PR.
=> remove use of util.Errorf for returning errors

.github/workflows/test.yml, README.md, event_manager_test.go, go.mod, go.sum, native_bucketing/bucketing.go, native_bucketing/event_queue.go, native_bucketing/event_queue_test.go, native_bucketing/murmurhash.go, native_bucketing/murmurhash_test.go, wasm_bucketing_test.go
Turning on the race detector in the unit tests turned up a couple of issues. The event queue ones were just caused by sketchy workarounds in the tests, but the library we were using for murmurhash was also causing an error.
Context on the cause is in this Github issue:
https://github.com/spaolacci/murmur3/issues/34
I switched to using twmb/murmur3, which doesn't trigger the race detector, appears to produce the same output, and is slightly faster.
=> DVC 7411: Fix race conditions and turn on race detector

.github/workflows/release.yml
This will update the version in `version.go` as long as it matches the pattern `vN.N.N*` to the tag minus its `v` prefix. The run will fail if the tag doesn't match, so we'll have to remember to check for that.
=> DVC-7444: Release workflow for updating version.go

bucketing/segmentation.go, bucketing/segmentation_test.go
This fixes a bug where audienceMatch filters were being short-circuited because of a bad type cast in the segmentation logic. The unit tests didn't catch it because a non-pointer type was also provided there, instead of the pointer type that the real config would have been parsed into.
=> fix casting of audienceMatch filters

bucketing/model_filters_test.go, bucketing/segmentation_test.go
Adding tests for common basic UserFilter configurations to replicate what we do in the segmentation tests in jssdks/localbucketing
=> DVC-7595 - basic user filter tests

bucketing/event_queue.go, configmanager.go, configuration.go, version.go
I added timeouts to the HTTP clients - it's a gotcha with the Go net/http client that the client can basically block forever under some conditions if a timeout isn't set.
=> Bump version and fix http client timeouts

testing_helpers.go
Noticed that this was complaining in tests even when not used. Because it was part of the init that seemed like unnecessary noise for clients.
=> set defaults for test options

README.md, client.go, client_test.go, example/cloud/main.go, example/local/main.go
In concert with other SDKs, update public references of `DVC` to `DevCycle`. Most of this work has already been done, mainly just updating some environment variables.
=> fix: DVC-8025 rename DVC references to DevCycle

configmanager.go
- before we were storing the etag for use in future CDN requests even if the config itself was not stored due to a validation error
- reverse the order of the operations so that the config is validated and stored first, and then the etag is set if that succeeds
=> fix: only set etag for requests after config is successfully validated and stored

bucketing/config_manager.go, client.go, client_native_bucketing.go, configmanager.go, configmanager_test.go
- make sure there's one source of truth for stored configs and etags
- configmanager now does not hold etag or config data at all, and gets everything from the bucketing package
=> chore: move all config storage and etag to localbucketing storage layer

bucketing/event_queue.go, bucketing/event_queue_test.go, bucketing/model_config_body.go, client.go, client_native_bucketing.go, configmanager.go, event_manager.go, example/cloud/main.go, example/local/main.go
- add event fields for the config and client identifiers
=> feat: add event fields

.github/workflows/bench.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/test_examples.yml
- update release action to use v2.3.0
- update setup-go to v5
- update lint-go to v4
- update actions/checkout and actions/cache to v4
=> chore: Fix release action

.github/workflows/test.yml, api/model_client.go, client.go, client_test.go, configmanager.go, configmanager_test.go, configuration.go, event_manager.go, event_manager_test.go, openfeature_provider_test.go, ssemanager.go, testing_helpers.go, testing_helpers_test.go
- Change our test initialization strategy to do the following:
- Never use the same sdk key - this causes a race condition in some cases due to spinning up and destroying config mocks.
- Start and stop the mocks only once in the test overall, help prevent the race conditions on tests only.
- Generate test SDK keys in a helper instead of the test function
- Create a threadsafe setup for handling SSE updates and polling/sse handoffs.
=> feat: SSE Config Consolidator Event Flow

configmanager.go
When the URL is the same - it was de-duplicated prematurely.
=> fix: Always set the SSE URL - ignore empty strings

client.go, client_test.go, configmanager.go, configmanager_test.go, configuration.go, event_manager.go, event_manager_test.go, openfeature_provider_test.go, testing_helpers_test.go
Also set clientdate on sdkconfig events, and regular tracked events.
=> fix: Ignore older config lastmodified timestamps when fetching a config.

api/model_public_project.go, bucketing/bucketing.go, bucketing/bucketing_test.go, bucketing/model_target.go, bucketing/testdata/fixture_test_config.json, bucketing/testdata/fixture_test_v2_config.json
- feat: add support for alternate key bucketing rollouts and random distributions
- supports String, Number and Boolean types for alternate keys
- chore: updates test data and test cases to ensure consistent bucketing for users with and without the alternate key defined
=> feat: Add support for alternate key bucketing

configmanager.go, configuration.go, testing_helpers_test.go
- enable SSE connetions by default, add `DisableRealtimeUpdates` option
- depricate `EnableBetaRealtimeUpdates` option
feat: enable SSE connections by default
=> feat: enable SSE connections by default

.github/workflows/test.yml, client.go, client_test.go, configmanager.go
This only needs to check whether or not the local bucketing engine is set properly. Not whether the client is initialized.
=> fix: Allow client custom data to be set prior to initialization for a given SDK Key

.github/workflows/run-test-harness.yml, aliases.go, api/model_variable.go, bucketing/bucketing.go, bucketing/config_manager.go, bucketing/configuration.go, client.go, client_hooks_test.go, client_native_bucketing.go, config_metadata_test.go, eval_hook.go, eval_hook_runner.go, eval_hook_test.go, evaluation_metadata.go, example/hooks/main.go, openfeature_provider_test.go
- create evaluation metadata with `_feature` as `FeatureId`
- pass in metadata with after and onFinally
=> feat: pass evaluation metadata to after and finally hooks
