DevCycleHQ/go-server-sdk

README.md
client.go
configuration.go
example/main.go

- add DVCOptions struct with EnableEdgeDB param
- update DVCClient to use DVCOptions
- add enableEdgeDB queryParam is DVCOptions.EnableEdgeDB is set to true for the DVCClient
- update Example App and Readme to show how to use DVCOptions

enable edge db support

---

.github/run-test-harness.yml

Add github action to run test harness on PR

feat: run test harness repo on PR

---

api_devcycle.go
api_devcycle_test.go
client.go
eventqueue_test.go
example/cloud/main.go
example/local/main.go

- remove needing to pass in an auth object for each client method

chore: removed usage of auth object passing into each method

---

api_devcycle.go
model_variable.go

- determine correct Type field value from default value type
- return error if type cannot be determined
- always serialize isDefaulted
- use private structs for Variable type inheritence

fix variable interface to set type correctly etc.

---

eventqueue.go
model_event.go
model_platformdata.go

* fix event payload format to send `batch`
* set `sdkType` to `server`

fix: event payload format

---

configmanager.go
eventqueue.go

instead of creating a global variable for each channel that is used to close config manager and events queue, use a channel attached to the instance for each instance

scope closing channels to client rather than using global vars

---

client.go
client_test.go
configmanager.go

- fix logic for retryable errors to check for 5xx errors

fix retryable error logic and swallow initialization errors

---

model_event.go

add back omitempty for optional event fields

add back some omitempty

---

eventqueue.go
localbucketing.go
localbucketing_test.go

Fix allocation to assume no conversion from utf8 is needed - just byte padding.

Fix UTF-16 handling

---

localbucketing.go

- update error logging to log file name and line numbers
- ensure that abort log message is handled correctly

Error logging changes

---

localbucketing.go
localbucketing_test.go

- fix behaviour when reserved memory blocks are too small and new memory is dynamically allocated
- previously, any dynamic allocation would attempt to unpin the ptr representing its data, however this ptr actually pointed to a permanently reserved block of memory for storing header information about the separately-reserved byte array
- it was then incorrectly unpinning this header, which made it liable to be garbage collected, thus breaking the ability to pass byte buffers into WASM

fix local bucketing unpinning buffer data

---

eventqueue.go

This fixes a slow goroutine leak in the event queue client. The response body was not automatically closed or read to completion when a successful API request was made.
I tested before and after with a loadtest, and it appears to fix this particular leak.

Always read and close response body in event queue

---

eventqueue.go

This stops the automated ticker from running when both `DisableAutomaticEventLogging` and `DisableCustomEventLogging` are true.

Disable automated event flush ticker when all sources of events are disabled

---

.github/workflows/test.yml
client_native.go
client_wasm.go
native_bucketing/placeholder.go

- add new native_bucketing package and files for alternate client implementations
- Run unit tests on native bucketing build

DVC-6781: new package and build for native bucketing

---

example/cloud/main.go
example/local/main.go

Basically just making the two examples somewhat configurable and showing more info about the resulting variables.

Update examples to show more useful info

---

api/model_event.go
api/model_user_data.go
client_native_bucketing.go
client_test.go
configuration.go
native_bucketing/aliases.go
native_bucketing/config_manager.go
native_bucketing/configuration.go
native_bucketing/constants.go
native_bucketing/event_queue.go
native_bucketing/event_queue_test.go

Currently basing into rob's PR base - but can be rebased onto main once merged.

DVC-6788 - Native event queue

---

native_bucketing/event_queue.go

This fixes the crash in the current native event queue implementation by using a cancelable context to signal the event processing goroutine to clean itself up. Closing the channels asynchronously resulted in the goroutine reading empty structs (a read from a closed channel returns the empty value), so this makes the shutdown path safe.

Use cancelable context to close channels safely

---

README.md
bench-dd/README.md

Adding info about native bucketing feature and updated benchmark server settings

Updating readme files

---

aliases.go
eventqueue_test.go
native_bucketing/event_queue.go
native_bucketing/event_queue_test.go

- add aliases for Logger, DiscardLogger, SetLogger
- fix delays and potential flakiness in event tests
- remove unnecessary debug logs

DVC 7187: Restore logs API and reduce noise

---

.github/workflows/bench.yml
api/model_event.go
bench-dd/go.mod
bench-dd/main.go
client.go
client_test.go
configuration.go
eventqueue.go
native_bucketing/event_queue.go
testing_helpers.go

Evaluating event payloads and track metrics to Datadog

DVC-7189 collect event bench metrics

---

bucketing/bucketing.go
bucketing/configuration.go
bucketing/event_queue.go
bucketing/event_queue_test.go
client.go
client_native_bucketing.go
client_test.go
configmanager.go
configuration.go

Allow overriding platformdata
Allow bypassing the variable default type check
Properly pass platformdata into native code

Allow bypassing the variable default type checks; PlatformData passthroughs

---

.github/workflows/test.yml

Example of a breaking run:
https://github.com/DevCycleHQ/go-server-sdk/actions/runs/5061970435/jobs/9086901941?pr=195

Test for zero allocation flow

---

bucketing/model_filters_test.go

Most of the tests were already handled, just did some tweaks and adding more coverage

DVC-7596-checkStringsFilter

---

bucketing/model_filters_test.go
bucketing/segmentation_test.go

Porting a bunch of unit tests for checkCustomData() from JS/TS

DVC-7599 check custom data filter

---

bucketing/segmentation_test.go

added some additional tests on how custom data is combined and evaluated, as well as priority of User.customData & User.privateCustomData over the global clientCustomData

more unit tests around custom data

---

bucketing/segmentation_test.go

Not sure this one was 100% necessary but I ported it over from `js-sdks` anyway.  It just confirms that the audience filters match as expected when using platform UserFilters.

DVC-7600 - filter audience unit tests

---

bucketing/bucketing_test.go

The test cases from the JIRA were mostly covered all ready, i just added some more cases validating how user.CustomData, user.PrivateCustomData and global clientCustomData are combined to bucket users or exclude them from features. 
Added a couple comments and renamed a few variables.

DVC-7614 - 

---

.github/workflows/release.yml

Also adds the ability to select which part of the version to bump.

fix: update release workflow to use prepare-release and create-release (DVC-8203)

---

bucketing/bucketing_test.go
bucketing/config_manager.go
bucketing/config_manager_test.go
bucketing/event_queue.go
bucketing/event_queue_test.go
bucketing/model_config_body.go
bucketing/model_config_body_test.go
client_native_bucketing.go
client_test.go
configmanager.go
configmanager_test.go

feat: track rayid in agg events

---

bucketing/constants.go
bucketing/segmentation.go
bucketing/segmentation_test.go

- adds new filters `startWith` and `endWith` for string comparison

feat: add new filters to go bucketing logic

---

.github/workflows/run-test-harness.yml
configmanager.go
configmanager_test.go
testing_helpers_test.go

- update config url and tests to v2

feat: update config url to support v2 configs

---

bucketing/bucketing_test.go

-  chore: updates test to include random distribution percentages with 4 decimal places

chore: update BucketingDistribution test to 4 decimal places

---

.github/workflows/lint.yml
.github/workflows/run-test-harness.yml
.github/workflows/test.yml
api/model_evalreason.go
api/model_variable.go
bench-dd/main.go
bucketing/bucketing.go
bucketing/bucketing_test.go
bucketing/constants.go
bucketing/event_queue.go
bucketing/event_queue_test.go
bucketing/model_config_body.go
bucketing/model_filters.go
bucketing/model_filters_test.go
bucketing/model_target.go
bucketing/model_target_test.go
bucketing/segmentation.go
client.go
client_native_bucketing.go
client_test.go
configmanager.go
event_manager.go
event_manager_test.go
example/local/main.go
request.go
ssemanager.go
testing_helpers_test.go

Add eval reasons to aggVariableEvaluated and aggVariableDefaulted
COR-3428

feat: eval reasons
